## Numpy

In [148]:
import numpy as np

In [149]:
a=np.arange(1,21).reshape(2,10)

In [150]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#Aggregate functions

In [151]:
a.sum()

210

In [152]:
a.min()

1

In [153]:
a.max()

20

In [154]:
a.mean()

10.5

In [155]:
arr2d=np.arange(1,21).reshape(2,10)

In [156]:
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [157]:
# Finding the minimum value in a NumPy array:

min_val = np.min(arr2d)
print(min_val)
max_val = np.max(arr2d)
print(max_val)

1
20


In [158]:
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
## Arithmetic operator

In [159]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
arr2= arr*3
arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [161]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [163]:
arr+arr2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [164]:
np.add(arr,arr2)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [165]:
arr2-arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [166]:
arr/arr2

array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [167]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [168]:
arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [173]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [172]:
arr[arr < 5]

array([1, 2, 3, 4])

In [174]:
arr == arr2

array([False, False, False, False, False, False, False, False, False,
       False])

In [175]:
arr2=np.arange(1,11)

In [176]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
# Finding the mean of a NumPy array:

mean_val = np.mean(arr2)
mean_val

5.5

In [178]:
# Finding the median of a NumPy array:

median_val = np.median(arr)
median_val

5.5

In [179]:
# Finding the standard deviation of a NumPy array:

std_val = np.std(arr)
std_val

2.8722813232690143

In [181]:
var_val = np.var(arr)
var_val

8.25

In [182]:
# Performing element-wise operations on NumPy arrays:

arr_squared = arr ** 2
arr_squared

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### Indexing and slicing NumPy arrays:

In [183]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
arr[0]

1

In [185]:
arr[1:4]

array([2, 3, 4])

In [186]:
arr[1:4:2]

array([2, 4])

In [187]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [188]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [189]:
#Exercise

# create an array of data
data = np.arange(100)

# calculate the mean
mean = np.mean(data)
print("Mean:", mean)

# calculate the median
median = np.median(data)
print("Median:", median)

# calculate the variance
variance = np.var(data)
print("Variance:", variance)

# calculate the standard deviation
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# calculate the minimum and maximum values
minimum = np.min(data)
maximum = np.max(data)
print("Minimum:", minimum)
print("Maximum:", maximum)


Mean: 49.5
Median: 49.5
Variance: 833.25
Standard deviation: 28.86607004772212
Minimum: 0
Maximum: 99


In [190]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [191]:
a[0]

array([1, 2, 3, 4, 5])

In [192]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [193]:
a[0,3]

4

In [196]:
a[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [194]:
a[0,3:5]

array([4, 5])

In [195]:
a[2,1]

12

In [197]:
#random.rand():- random values that are uniformly distributed between 0 and 1.
np.random.rand(2, 3)

array([[0.08647799, 0.40438464, 0.63651876],
       [0.50196085, 0.83474376, 0.75744338]])

In [198]:
np.random.rand(2, 3, 4)

array([[[0.39482535, 0.01237998, 0.36907705, 0.22936771],
        [0.36869602, 0.74845491, 0.90981206, 0.98986433],
        [0.57496575, 0.20942201, 0.15879219, 0.6177059 ]],

       [[0.34296483, 0.9791704 , 0.26258339, 0.35233766],
        [0.23800872, 0.61451027, 0.19066325, 0.89161034],
        [0.06035148, 0.61636177, 0.68919126, 0.53283678]]])

In [199]:
print(np.random.rand(2, 3, 4, 5))

[[[[3.08305208e-01 4.37962779e-01 5.03782050e-01 6.55803546e-01
    6.28305906e-01]
   [7.26868783e-01 5.86383150e-01 3.87715415e-01 7.98643391e-01
    5.60987945e-01]
   [9.82969047e-01 6.30740452e-01 7.22589927e-01 9.04415168e-02
    8.25453626e-01]
   [3.90282247e-01 8.62085355e-01 7.39986228e-02 5.67419901e-01
    9.61552661e-01]]

  [[1.24383068e-01 8.29863781e-05 4.71202019e-01 8.79741188e-01
    8.04748127e-01]
   [8.11453844e-01 1.34865373e-01 5.91135942e-01 7.32411639e-01
    4.46622587e-01]
   [7.20284278e-01 5.58859861e-01 7.68489510e-01 8.13757073e-01
    3.74667181e-01]
   [8.59507557e-01 1.51296200e-02 9.83182340e-01 6.33747377e-01
    6.09014126e-01]]

  [[6.77001847e-01 7.87081805e-01 8.42710071e-01 2.96100632e-01
    9.69446236e-01]
   [9.08969035e-01 9.08117110e-01 4.30847755e-01 1.41421370e-01
    8.98111247e-01]
   [5.35827326e-01 4.75438475e-01 1.73000845e-01 5.32492506e-01
    8.11666058e-01]
   [3.23076311e-01 4.96770642e-01 1.07756863e-01 1.93762742e-01
    3.54

In [200]:
#random.randn() :- random values that are normally distributed with a mean of 0 and a standard deviation of 1
np.random.randn(2, 3)

array([[-1.16749356,  0.08595726,  0.24403274],
       [ 1.58583741,  0.02635008,  0.57329594]])

In [201]:
np.random.randn(2, 3,2)

array([[[ 0.84073203, -1.09215534],
        [-1.61004871,  1.36906246],
        [ 0.49142119,  0.03881809]],

       [[-1.46872042, -1.16138515],
        [ 1.38705478, -0.58231577],
        [ 0.37497776, -1.01758494]]])

In [206]:
np.random.randn(20, 30).mean()

-0.01353706047181204

In [205]:
np.random.randn(200, 300).mean()

0.0030793259654527173

In [207]:
np.random.randn(20, 30).var()

1.0761094025593767

In [208]:
np.random.randn(200, 300).mean()

0.009922638546309445

In [209]:
np.random.randn(200, 3000).var()

0.9982898523989281

### Matrix

In [210]:
# Define two matrices to multiply
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

In [211]:
matrix1

array([[1, 2],
       [3, 4]])

In [212]:
matrix2

array([[5, 6],
       [7, 8]])

In [213]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 32]])

In [214]:
# Method 1: Using np.dot()
result1 = np.dot(matrix1, matrix2)
print(result1)

[[19 22]
 [43 50]]


In [215]:
# Method 2: Using @ operator
result2 = matrix1 @ matrix2
print(result2)

[[19 22]
 [43 50]]


In [216]:
# Compute the determinant


matrix = np.array([[1, 2], [3, 4]])

det = np.linalg.det(matrix)
print(det)


-2.0000000000000004


In [217]:


# calculate the inverse
matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [218]:
#cross check     
matrix @ matrix_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [ ]:
#Create matrix with initial values

In [219]:
z = np.zeros([5,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [220]:
o = np.ones([5,3])
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [221]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [225]:
# copy

a = np.array([[ 0 , 1 , 2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10 ,11]])

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [227]:
b = a  # Shallow COpy / View 

a[0,0] = 99


In [228]:
a

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
b

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [230]:
print(b is a )
print(a is b )

True
True


In [231]:
print(b)
print(id(a))
print(id(b))

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2258034283888
2258034283888


In [232]:
print(b is a)

True


In [234]:
# deep copy
c =  a.copy()

In [235]:
c[0,0] = 999

In [236]:
print(c is a )
print(c is b )

False
False


In [237]:
print(a)
print(c)


[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [238]:
print(a)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [239]:
a.T

array([[99,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [240]:
a.transpose()

array([[99,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Pandas

In [241]:
import pandas as pd

In [244]:
# Series :- one-dimensional labeled array  ( #single column)
s1 = pd.Series(data=[10,20,30], index=['a', 'b' ,'c'])
s1

a    10
b    20
c    30
dtype: int64

In [ ]:
index=["a","b","c"]

In [252]:
"a b c".split(" ")

['a', 'b', 'c']

In [245]:
 pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [246]:
s1.shape

(3,)

In [247]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [248]:
s1 = pd.Series(data=[10,20,30])

In [250]:
s1

0    10
1    20
2    30
dtype: int64

In [249]:
s1.index

RangeIndex(start=0, stop=3, step=1)

In [251]:
s1.columns

AttributeError: 'Series' object has no attribute 'columns'

In [ ]:
"a b c".split(" ")

In [254]:
labels = ("a b c".split(" "))
mydata = [10,20,30]
s1 = pd.Series(data=mydata, index=labels)
print(s1)

a    10
b    20
c    30
dtype: int64


In [255]:
labels

['a', 'b', 'c']

In [259]:
pd.Series(mydata,labels) # parameters are in oreder , so no need to specify

a    10
b    20
c    30
dtype: int64

In [260]:
pd.Series(labels,mydata)

10    a
20    b
30    c
dtype: object

In [261]:
pd.Series(mydata) # if lable  i.e index is not provided

0    10
1    20
2    30
dtype: int64

In [262]:
pd.Series([2,3,4])

0    2
1    3
2    4
dtype: int64

In [263]:
pd.Series((2,3,4))

0    2
1    3
2    4
dtype: int64

In [264]:
d1  = {'a' :10,
      'b':20,
      'c':30}
s1 = pd.Series(d1)
s1

a    10
b    20
c    30
dtype: int64

In [265]:
d2  = {'a' :10,
      'b':20,
      'c':30}
s2 = pd.Series(d2)
s2

a    10
b    20
c    30
dtype: int64

In [269]:
d3  = {'a' :10,
      'b':20,
      'd':30}
s3 = pd.Series(d3)
s3

a    10
b    20
d    30
dtype: int64

In [266]:
s1

a    10
b    20
c    30
dtype: int64

In [267]:
s2

a    10
b    20
c    30
dtype: int64

In [270]:
s3

a    10
b    20
d    30
dtype: int64

In [268]:
s1+s2  #[1,2,3]

a    20
b    40
c    60
dtype: int64

In [271]:
s2+s3

a    20.0
b    40.0
c     NaN
d     NaN
dtype: float64

In [272]:
s2

a    10
b    20
c    30
dtype: int64

In [274]:
s2['c']

30

In [275]:
s1.size

3

In [276]:
s1.shape

(3,)

In [278]:
s1.ndim

1

In [279]:
s2 =  s1 #shallow copy
s1

a    10
b    20
c    30
dtype: int64

In [280]:
s1["a"]=100

In [281]:
s1

a    100
b     20
c     30
dtype: int64

In [282]:
s2

a    100
b     20
c     30
dtype: int64

In [283]:
s3= s2.copy()  #deep copy

In [284]:
s2["b"]=222

In [285]:
s2

a    100
b    222
c     30
dtype: int64

In [286]:
s3

a    100
b     20
c     30
dtype: int64

In [ ]:
# Dataframes :-two-dimensional labeled array that can hold multiple Series, where each Series can have a different data type
# pd.DataFrame(data,index,columns)


In [287]:
np.random.randn(6,6)

array([[-0.19372264, -1.79282631,  1.23147536, -0.95466035, -0.82073547,
        -0.61983892],
       [ 1.2744389 , -1.41330175, -0.54377923, -1.56443826, -0.97769804,
         0.93287889],
       [-0.64958662, -0.35592185, -0.27036306,  0.76406525,  0.7469691 ,
        -0.05138009],
       [ 1.17665056, -1.82014055, -0.27485319,  0.78817545, -1.03226548,
         0.31464205],
       [ 2.04276784, -0.48815762, -2.20234464, -0.02752915,  0.53059595,
         1.20783485],
       [-0.11315589, -1.70100786,  0.63951135,  1.05674522, -1.11281859,
        -0.91898583]])

In [288]:
df2 = pd.DataFrame(np.random.randn(6,6))
df2

0         1         2         3         4         5
0 -1.373269 -0.686463 -0.293660 -0.160649  1.560478 -0.472327
1  0.760929  0.607378 -0.396619  1.439086  0.325656  0.008949
2 -0.681299 -1.106735 -1.626644 -0.607721  0.390539  0.645432
3  0.116396 -2.482629 -1.226625 -0.639398 -1.259891 -1.161170
4 -0.736978  0.848164 -2.079985  1.920456  1.468108  1.130826
5 -0.522100 -0.247149  0.215559  2.263255  0.093919 -2.124291

In [289]:
df2 = pd.DataFrame(np.random.randn(6,6),['A', 'B', 'C', 'D' ,'E', 'F'])
df2

0         1         2         3         4         5
A  1.019120 -0.118846  0.469120 -0.623696  0.876962 -0.468243
B -1.038802 -0.524464  0.164416 -0.207366  0.807808 -0.466845
C  0.228508  1.791355  1.507773  1.095993  0.769572 -0.112229
D  0.652169  1.165056  1.422862 -1.050810  1.806015 -1.441687
E -0.302276  0.382891 -1.300359 -0.956577 -0.212987  0.328716
F -0.122026  0.269380  0.310373  0.463425 -0.801402 -0.297801

In [290]:
df2 = pd.DataFrame(np.random.randn(6,6),['A', 'B', 'C', 'D' ,'E', 'F'],['U', 'V', 'W' ,'X' ,'Y', 'Z'])
df2


U         V         W         X         Y         Z
A -0.055725  2.216878 -1.062682  0.463589  0.506563  0.193041
B -0.983368  2.200271 -1.690854 -0.983740 -0.830152  2.099737
C  0.907088  0.715187  0.374504  0.379286  0.223340  0.299570
D  2.073867 -1.059064 -1.198760 -0.944476 -2.094775  0.884029
E -0.152931  0.922471 -1.059885 -0.142911 -1.234753  0.797132
F  2.822414  0.385589 -0.216513 -1.268678 -0.047951  1.839721

In [291]:

df2 = pd.DataFrame(np.random.randn(6,6),list("A B C D E F".split(" ")) ,list("U V W X Y Z".split(" ") ))
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [292]:
df2.ndim

2

In [293]:
df2.size

36

In [294]:
df2.shape

(6, 6)

In [295]:
type(df2) # collection of serieas is a  DF

pandas.core.frame.DataFrame

##### Accessing columns 

In [296]:
# Accessing columns 
#  using dot
#  not recommended
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [297]:
df2.X

A   -0.168917
B    0.549419
C   -0.969244
D    0.616090
E    0.434619
F   -0.553653
Name: X, dtype: float64

In [298]:
df2.A

AttributeError: 'DataFrame' object has no attribute 'A'

In [299]:
#  [] for accessing the data
df2['Z']

A    0.248080
B   -0.378874
C    0.733151
D    1.963631
E    0.698382
F   -0.478671
Name: Z, dtype: float64

In [300]:
df2['A']

KeyError: 'A'

In [301]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [302]:
df2["U","V"]

KeyError: ('U', 'V')

In [304]:
#  [] for accessing multiple columns
df2[['X','Z']]

X         Z
A -0.168917  0.248080
B  0.549419 -0.378874
C -0.969244  0.733151
D  0.616090  1.963631
E  0.434619  0.698382
F -0.553653 -0.478671

In [303]:
# U and V
df2[['U','V']]

U         V
A  0.628910 -0.279470
B -1.000327 -0.018418
C -2.170053  0.258648
D -0.854696  0.856849
E  0.205118  0.293996
F  1.214149  0.541522

In [305]:
df2[["V","Y"]]

V         Y
A -0.279470  0.716216
B -0.018418 -0.032384
C  0.258648 -0.544527
D  0.856849 -0.892781
E  0.293996 -0.601275
F  0.541522 -0.243133

In [306]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [307]:
df2["A"]

KeyError: 'A'

In [308]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [309]:
#loc
df2.loc["A"]

U    0.628910
V   -0.279470
W    0.488236
X   -0.168917
Y    0.716216
Z    0.248080
Name: A, dtype: float64

In [310]:
df2.iloc["A"] # A is not an index

TypeError: Cannot index by location index with a non-integer key

In [311]:
df2.iloc[0] 

U    0.628910
V   -0.279470
W    0.488236
X   -0.168917
Y    0.716216
Z    0.248080
Name: A, dtype: float64

In [312]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [313]:
df2.loc["A":"C"]  # last index included

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151

In [ ]:
# arr[2:3,3:4]

In [314]:
df2.loc["A":"C"]["X"]

A   -0.168917
B    0.549419
C   -0.969244
Name: X, dtype: float64

In [316]:
df2.loc["A":"C","X"]

A   -0.168917
B    0.549419
C   -0.969244
Name: X, dtype: float64

In [319]:
df2.loc["A":"C"][["X","Y"]]

X         Y
A -0.168917  0.716216
B  0.549419 -0.032384
C -0.969244 -0.544527

In [318]:
df2.loc["A":"C",["X","Y"]]   # arr[2:3,3:4]

X         Y
A -0.168917  0.716216
B  0.549419 -0.032384
C -0.969244 -0.544527

In [320]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [322]:
df2.loc["E":"F",["W","X"]]

W         X
E -1.232134  0.434619
F -0.722230 -0.553653

In [324]:
df2.loc["E":"F"][["W","X"]]

W         X
E -1.232134  0.434619
F -0.722230 -0.553653

In [327]:
df2.iloc[1:3][["U","X"]]

U         X
B -1.000327  0.549419
C -2.170053 -0.969244

In [329]:
df2.iloc[1:3][["U","V","X"]]

U         V         X
B -1.000327 -0.018418  0.549419
C -2.170053  0.258648 -0.969244

In [330]:
df2

U         V         W         X         Y         Z
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671

In [331]:
# Adding a new column
df2["New_col"] = df2["Z"]*2
df2

U         V         W         X         Y         Z   New_col
A  0.628910 -0.279470  0.488236 -0.168917  0.716216  0.248080  0.496161
B -1.000327 -0.018418  2.558664  0.549419 -0.032384 -0.378874 -0.757748
C -2.170053  0.258648 -0.143731 -0.969244 -0.544527  0.733151  1.466302
D -0.854696  0.856849  1.391035  0.616090 -0.892781  1.963631  3.927263
E  0.205118  0.293996 -1.232134  0.434619 -0.601275  0.698382  1.396764
F  1.214149  0.541522 -0.722230 -0.553653 -0.243133 -0.478671 -0.957342

In [332]:
# deleting a column 

df2.drop('X')
df2

KeyError: "['X'] not found in axis"

In [335]:
dd=df2.drop('X',axis=1)


In [336]:
dd

U         V         W         Y         Z   New_col
A  0.628910 -0.279470  0.488236  0.716216  0.248080  0.496161
B -1.000327 -0.018418  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053  0.258648 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  0.856849  1.391035 -0.892781  1.963631  3.927263
E  0.205118  0.293996 -1.232134 -0.601275  0.698382  1.396764
F  1.214149  0.541522 -0.722230 -0.243133 -0.478671 -0.957342

In [341]:
df2.drop("X",axis=1,inplace=True)

In [342]:
df2

U         V         W         Y         Z   New_col
A  0.628910 -0.279470  0.488236  0.716216  0.248080  0.496161
B -1.000327 -0.018418  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053  0.258648 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  0.856849  1.391035 -0.892781  1.963631  3.927263
E  0.205118  0.293996 -1.232134 -0.601275  0.698382  1.396764
F  1.214149  0.541522 -0.722230 -0.243133 -0.478671 -0.957342

In [343]:
df2.drop('X',axis=0)
df2

KeyError: "['X'] not found in axis"

In [344]:
df2

U         V         W         Y         Z   New_col
A  0.628910 -0.279470  0.488236  0.716216  0.248080  0.496161
B -1.000327 -0.018418  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053  0.258648 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  0.856849  1.391035 -0.892781  1.963631  3.927263
E  0.205118  0.293996 -1.232134 -0.601275  0.698382  1.396764
F  1.214149  0.541522 -0.722230 -0.243133 -0.478671 -0.957342

In [345]:
df2.drop('V',axis=1)

U         W         Y         Z   New_col
A  0.628910  0.488236  0.716216  0.248080  0.496161
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  1.391035 -0.892781  1.963631  3.927263
E  0.205118 -1.232134 -0.601275  0.698382  1.396764
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342

In [346]:
df2

U         V         W         Y         Z   New_col
A  0.628910 -0.279470  0.488236  0.716216  0.248080  0.496161
B -1.000327 -0.018418  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053  0.258648 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  0.856849  1.391035 -0.892781  1.963631  3.927263
E  0.205118  0.293996 -1.232134 -0.601275  0.698382  1.396764
F  1.214149  0.541522 -0.722230 -0.243133 -0.478671 -0.957342

In [347]:
df2.drop('V',axis=1,inplace=True) # inplace=True for permanent deletion
df2

U         W         Y         Z   New_col
A  0.628910  0.488236  0.716216  0.248080  0.496161
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  1.391035 -0.892781  1.963631  3.927263
E  0.205118 -1.232134 -0.601275  0.698382  1.396764
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342

In [348]:
df2

U         W         Y         Z   New_col
A  0.628910  0.488236  0.716216  0.248080  0.496161
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748
C -2.170053 -0.143731 -0.544527  0.733151  1.466302
D -0.854696  1.391035 -0.892781  1.963631  3.927263
E  0.205118 -1.232134 -0.601275  0.698382  1.396764
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342

In [349]:
df2["NN"]=5

In [350]:
df2

U         W         Y         Z   New_col  NN
A  0.628910  0.488236  0.716216  0.248080  0.496161   5
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5
D -0.854696  1.391035 -0.892781  1.963631  3.927263   5
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [352]:
df2["empty"]=""

In [353]:
df2

U         W         Y         Z   New_col  NN empty
A  0.628910  0.488236  0.716216  0.248080  0.496161   5      
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5      
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5      
D -0.854696  1.391035 -0.892781  1.963631  3.927263   5      
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5      
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [354]:
df2.drop("D")

U         W         Y         Z   New_col  NN empty
A  0.628910  0.488236  0.716216  0.248080  0.496161   5      
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5      
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5      
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5      
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [356]:
df2.drop("D",axis=0)

U         W         Y         Z   New_col  NN empty
A  0.628910  0.488236  0.716216  0.248080  0.496161   5      
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5      
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5      
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5      
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [357]:
df2

U         W         Y         Z   New_col  NN empty
A  0.628910  0.488236  0.716216  0.248080  0.496161   5      
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5      
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5      
D -0.854696  1.391035 -0.892781  1.963631  3.927263   5      
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5      
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [358]:
df2.drop("D",axis=0,inplace=True)

In [359]:
df2

U         W         Y         Z   New_col  NN empty
A  0.628910  0.488236  0.716216  0.248080  0.496161   5      
B -1.000327  2.558664 -0.032384 -0.378874 -0.757748   5      
C -2.170053 -0.143731 -0.544527  0.733151  1.466302   5      
E  0.205118 -1.232134 -0.601275  0.698382  1.396764   5      
F  1.214149 -0.722230 -0.243133 -0.478671 -0.957342   5

In [360]:
df2.drop("U","empty",axis=1)

C:\Users\dell\AppData\Local\Temp\ipykernel_9424\2465727404.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2.drop("U","empty",axis=1)


TypeError: drop() got multiple values for argument 'axis'

In [361]:
df2.drop(["U","empty"],axis=1)

W         Y         Z   New_col  NN
A  0.488236  0.716216  0.248080  0.496161   5
B  2.558664 -0.032384 -0.378874 -0.757748   5
C -0.143731 -0.544527  0.733151  1.466302   5
E -1.232134 -0.601275  0.698382  1.396764   5
F -0.722230 -0.243133 -0.478671 -0.957342   5

In [362]:
df2.drop(["U","empty"],axis=1,inplace=True)

In [363]:
df2

W         Y         Z   New_col  NN
A  0.488236  0.716216  0.248080  0.496161   5
B  2.558664 -0.032384 -0.378874 -0.757748   5
C -0.143731 -0.544527  0.733151  1.466302   5
E -1.232134 -0.601275  0.698382  1.396764   5
F -0.722230 -0.243133 -0.478671 -0.957342   5