# Numpy

In [2]:
import numpy as np

In [3]:
# Creating array:

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
# Creating  2D array:

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# arange
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr= np.arange(1,100,10)
arr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
len(arr)

10

In [9]:
[2,3,"one",4.5]

[2, 3, 'one', 4.5]

In [11]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [12]:
np.array([1, 2, 3.0, 4, 5])

array([1., 2., 3., 4., 5.])

In [13]:
np.array([1, 2, "3.0", 4, 5])

array(['1', '2', '3.0', '4', '5'], dtype='<U11')

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [20]:
arr = np.arange(1,11)

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Reshape:

arr_reshaped = arr.reshape((2,5))
arr_reshaped 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#np.reshape(data,shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [23]:
a=np.arange(1,21,2)

In [24]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
np.reshape(a,(2,5),"C")

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [26]:
np.reshape(a,(2,5),"F")

array([[ 1,  5,  9, 13, 17],
       [ 3,  7, 11, 15, 19]])

In [29]:
a.reshape((2,5),"C")

TypeError: 'tuple' object cannot be interpreted as an integer

In [30]:
a.reshape(2,5,order="C")

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [31]:
a.reshape(2,5,order="F")

array([[ 1,  5,  9, 13, 17],
       [ 3,  7, 11, 15, 19]])

In [32]:
arr_reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
# Transpose
#Method1
arr_transpose  = arr_reshaped.T
arr_transpose

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [34]:
#Method2
transpose  = arr_reshaped.transpose()
print(transpose)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [39]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,end,part)
a=np.linspace(0, 50, 10)
a

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [40]:
a=np.arange(0, 50, 10)
a

array([ 0, 10, 20, 30, 40])

In [37]:
len(a)

10

In [41]:
arr = np.linspace(0, 100, 10)
arr

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [43]:
np.array([2,3,4],dtype="float")

array([2., 3., 4.])

In [44]:
arr = np.linspace(0, 100, 10,dtype="int")
arr

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [45]:
a=np.arange(1,10,dtype='float')
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
a=np.arange(1,10,dtype='int')
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.shape

(9,)

In [48]:
a.ndim

1

In [49]:
a.size

9

In [50]:
a.dtype

dtype('int32')

In [51]:
b=np.array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [52]:
b

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [53]:
c=np.array([  0,  11,  22,  33.55,  44,  55,  66,  77,  88, 100])

In [54]:
c

array([  0.  ,  11.  ,  22.  ,  33.55,  44.  ,  55.  ,  66.  ,  77.  ,
        88.  , 100.  ])

In [ ]:
c.dtype

In [55]:
c=np.array([  0,  11,  "22",  33.55,  44,  55,  66,  77,  88, 100])

In [56]:
c

array(['0', '11', '22', '33.55', '44', '55', '66', '77', '88', '100'],
      dtype='<U32')

In [58]:
arr

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [60]:
#resize():- returns a new array with a new shape
#np.resize(array, new_shape)
np.resize(arr, (2, 5))

array([[  0,  11,  22,  33,  44,  55],
       [ 66,  77,  88, 100,   0,  11]])

In [ ]:
np.resize(arr, (2, 6))  #Diff between reshape and resize

In [61]:
#reshape
arr.reshape(2,5)

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88, 100]])

In [62]:
#reshape
arr.reshape(2,5,order="C")

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88, 100]])

In [63]:
#reshape
arr.reshape(2,5,order="F")

array([[  0,  22,  44,  66,  88],
       [ 11,  33,  55,  77, 100]])

In [64]:
arr

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [65]:
np.reshape(arr,(2,5))

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88, 100]])

In [66]:
np.reshape(arr,(2,5),'C')

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88, 100]])

In [67]:
np.reshape(arr,(2,5),'F')

array([[  0,  22,  44,  66,  88],
       [ 11,  33,  55,  77, 100]])

In [68]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
np.reshape(arr2,(4,5),'C')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
b = np.reshape(arr2,(4,5),'F')
b

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [71]:
b.shape #array shape

(4, 5)

In [72]:
b.ndim  # dimension

2

In [73]:
b.size  # no. arry elements

20

In [74]:
b.dtype #data type of array element (int,float,complex,bool,string,object)

dtype('int32')

In [75]:
b.dtype.name

'int32'

In [76]:
b

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [77]:
b.astype(float) #change data type

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [78]:
b.astype(int)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [80]:
c=b.reshape(2,10)
c

array([[ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18,  3,  7, 11, 15, 19]])

In [81]:
#ravel
c.ravel()

array([ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7,
       11, 15, 19])

In [83]:
c.reshape(20,)

array([ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7,
       11, 15, 19])

In [84]:
#append
c=np.arange(1,16).reshape((3,5))

d=np.arange(21,36).reshape((3,5))

print(c)
print("---------")
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
---------
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [85]:
np.append(c,d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [86]:
np.append(c,d,axis=0)  #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [88]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [89]:
d

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [87]:
np.append(c,d,axis=1)  #column

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [90]:
# combining
# M1)concatenate
np.concatenate((c,d),axis=0) #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [91]:
np.concatenate((c,d),axis=1) #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [92]:
# M2)
np.vstack((c,d))  #row qxis=0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [93]:
np.hstack((c,d)) #col qxis=1

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [94]:
# M3)
np.column_stack((c,d)) #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [95]:
np.row_stack((c,d)) #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [96]:
# M4)
np.r_[c,d] #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [97]:
np.c_[c,d]  #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [98]:
#splitting
a=np.r_[c,d]
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [101]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [102]:
k=np.vsplit(a,3)
k

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [103]:
a1,b1,c1=np.vsplit(a,3) # Split into 3 equally-sized sub-arrays

In [104]:
a1   # unpaking

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [105]:
b1

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [106]:
c1

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [107]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [109]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [111]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [114]:
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [112]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [115]:
np.vsplit(a,6)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35]])]

In [110]:
np.vsplit(a,4)

ValueError: array split does not result in an equal division

In [116]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [117]:
d

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [118]:
b=np.c_[c,d] 
b

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [119]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [120]:
np.hsplit(b,5)

[array([[ 1,  2],
        [ 6,  7],
        [11, 12]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14]]),
 array([[ 5, 21],
        [10, 26],
        [15, 31]]),
 array([[22, 23],
        [27, 28],
        [32, 33]]),
 array([[24, 25],
        [29, 30],
        [34, 35]])]

In [121]:
np.vsplit(b,3)

[array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25]]),
 array([[ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30]]),
 array([[11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])]