## map()

In [1]:

# map (fun ,ite)

In [54]:
listD = [11,22,33]
#[21,32,43]

q4 = list(map(lambda x:x+10,listD))
print(q4)

[21, 32, 43]


In [36]:
# map
list_score = [42,71,41,12,8,99]

def double_score(z):
#     for i in z:
        return(2*z)

In [37]:
double_score(list_score)

[42, 71, 41, 12, 8, 99, 42, 71, 41, 12, 8, 99]

In [40]:
# map (fun ,ite)
list(map(double_score,list_score))

[84, 142, 82, 24, 16, 198]

In [41]:
type(map(double_score,list_score))

map

In [43]:
list(map(lambda x :2*x,list_score))

[84, 142, 82, 24, 16, 198]

In [ ]:
#[1,2,4,6]
# [2,3,9,2]

In [45]:
list(map(lambda a,b : a+b,[1,2,4,6],[2,3,9,2]))

[3, 5, 13, 8]

In [46]:
#Find age if DOB year given
listA = [1989,1990,1991,1992]
listB =[] #[33,32,31,30]
for item in listA:
    listB.append(2023-item)
print(listB)

[34, 33, 32, 31]


In [50]:
# map
q2 = list(map(lambda x:2023-x,listA))
print(q2)

[34, 33, 32, 31]


In [51]:
# map
q2 = tuple(map(lambda x:2022-x,listA))
print(q2)

(33, 32, 31, 30)


In [52]:
listC = [1,2,3,4,5,6,7,8,9,10]
#[3,6,9,12,15,18,21,24,27,30]

In [53]:
#map(fn,list)
q3 = list(map(lambda x:x*3,listC))
print(q3)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


[21, 32, 43]


## filter()

In [55]:
list_score = [42,71,41,12,8,99]

In [ ]:
# filter
# filter (fn,iterable object)
def even_num(s):
    if s%2 !=0:
        return s

In [56]:
print(list(filter(even_num,list_score)))

[71, 41, 99]


In [57]:

listE = [22,33,44,55,22,33,44,55,66]
listF = []
#[55,55,66]

for item in listE:
    if item > 50:
        listF.append(item)
print(listF)

[55, 55, 66]


In [58]:
# filter 
q5 = list(filter(lambda x:x >= 50,[22,33,44,50,22,33,44,55,66]))
print(q5)

[50, 55, 66]


In [59]:
listG = [33,44,55,22,3,477,88,99]
print(list(filter(lambda x : x%2 == 0,listG))) #even

[44, 22, 88]


In [60]:
print(list(filter(lambda x : x%2 != 0,listG))) # odd

[33, 55, 3, 477, 99]


In [61]:
listF = ["Priyanka","Raj","Ganesh"]
print(list(filter(lambda x : len(x)  == 4,listF)))

[]


In [63]:
listF = ["Priyanka","Raj","Ganesh"]
print(list(filter(lambda x : x.startswith("G"),listF)))

['Ganesh']


### reduce()

In [64]:
# reduce
def all_sum(x):
    s = 0 
    for i in x:
        s = s + i
    return s

In [65]:
print(all_sum([1,2,3,4,5]))

15


In [71]:
print(reduce(lambda x ,y: x+y ,[1,2,3,4,5]))

NameError: name 'reduce' is not defined

In [73]:
from functools import reduce

In [74]:
print(reduce(lambda x ,y: x*y ,[1,2,3,4,5]))

120


In [75]:

listG = [1,2,5,10] # 18
sum = 0    # acc

for item in listG:
    sum = sum + item
print(sum)

18


In [76]:
from functools import reduce

print(reduce(lambda x,y:x+y,listG))

18


In [77]:
# print(reduce(lambda acc,nextval:acc+nextval,listG,5))
#[1,2,5,10] 
#acc 2
#itr 3 5 10 20
print(reduce(lambda x,y:x+y,listG,2))

20


In [78]:
# reduce
def all_sum(x):
    s = 0 
    for i in x:
        s = s + i
    return s

print(all_sum([1,2,3,4,5]))

15


In [79]:
print(reduce(lambda x ,y: x+y ,[1,2,3,4,5]))

15


In [80]:
print(reduce(lambda x ,y: x*y ,[1,2,3,4,5]))

120


## try ... except

In [81]:
a = 10
#b = 100
b = 0
c = a/b # ZeroDivisionError: division by zero if b = 0
print(c)

print("ok")

ZeroDivisionError: division by zero

In [86]:
try:
    a = 10
    # b = 100
    b = 0
    c = a/b # ZeroDivisionError: division by zero if b = 0
    print(c)
except ZeroDivisionError as e:   
    print("You have enterd wrong value of b , should not be zero")

    
print("ok")

You have enterd wrong value of b , should not be zero
ok


In [87]:
try:
    a = 10
    # b = 100
    b = 0
    c = a/b # ZeroDivisionError: division by zero if b = 0
    print(c)
except ZeroDivisionError as e:   
    print("You have enterd wrong value of b , should not be zero",e)

    
print("ok")

You have enterd wrong value of b , should not be zero division by zero
ok


In [88]:
try:
    a = 10
    # b = 100
    b = 0
    c = a/b # ZeroDivisionError: division by zero if b = 0
    print(c)
except FileNotFoundError as e:
    print("Some error occured ", e)
except IndexError as e:
    print("Element not found" , e )
except:
    print("Something wrong")

Something wrong


In [89]:
# 1. catch exception in below code using try... except 
# else print " Code Execution was successful"
try:
    list_z = [1,2,3,"a"]
    for i in range(3):
        if type(list_z[i]) == int:
            print("This is int")
        
        else:
            print("This is not int") 
except IndexError as e1:
    print("Error occured is:",e1)
except ZeroDivisionError:
    print("input should not be zero")
else:
    print ("Code Execution was successful")
finally:
    print("Code End")

print("Hi")

This is int
This is int
This is int
Code Execution was successful
Code End
Hi


In [90]:
# 2. catch exception in below code using try... except
# else print " Code Execution was successful"
# also close the file irrespective of operation on file
try:
    f = open(r"one.txt")
    print(f.read())
except FileNotFoundError as e2:
    print(f"Error occured is:",e2)
else:
    print (" Code Execution was successful")
finally:
    try:
        f.close()
        print("File closed")
    except:
        print("File not found" )

Error occured is: [Errno 2] No such file or directory: 'one.txt'
File not found


In [27]:
# # 3. catch exception in below code using try... except

try:
    print("Hello World)
except :
    print("Error occured is:")   # syntax erroe not handled

SyntaxError: EOL while scanning string literal (3391841874.py, line 4)

### raise Exception 

In [ ]:
def div1(a):
    # a = int(input("Enter an non zero number !!!"))
    if a == 0:
        raise ZeroDivisionError("Enter a non zero num")
    else:
        print(100/a)

In [117]:

# user defined exception


x = int(input("Enter an even number !!!"))
if x %2 != 0:
    raise Exception("Enter only even number")
else:
    print("The number is even ")

Enter an even number !!!5


Exception: Enter only even number

## Regular Expression (RegEx)

In [ ]:
# Python has a built-in package called re, which can be used to work with Regular Expressions.

import re

In [ ]:

# If the search is successful, re.search() returns a 
# match object; if not, it returns None.
# match = re.search(pattern, str)
str = "sun mop run"  # 'm\w\w' // [a-z][A-Z][0-9] // nor special symbol

# re.search(regex,str)
e = re.search(r'm\w\w',str)
print(e)
print(e.group())
print("-------")
#program2
str2 = "i am leanring langauge"
e2 = re.search(r'an\w\w',str2)
print(e2.group())

print("------------findall----------------")
# The re.findall() method returns a list of strings
#  containing all matches.
# If the pattern is not found, re.findall() 
# returns an empty list.
# program3
str3 = "sun mop run man mat" 
e3 = re.findall(r'm\w\w',str3)
print(e3)
for item in e3:
    print(item)

#program4
str4 = "sun sand surface sub"
e4 = re.findall(r'su\w',str4)
print(e4)
for item in e4:
    print(item)

print("------------match----------------")

#program5
str5 = "sun sand surface sub"
e6 = re.match(r's\w\w',str5)

if e6:
    print('occurence found')
    print(e6.group())
else:
    print('no occurence')

print("------------sub----------------")
# The syntax of re.sub() is: re.sub(pattern, replace, string)
# The method returns a string where matched occurrences are 
# replaced with the content of replace variable.
#program6
str6 = "I am learning javascript"
e7 = re.sub(r'javascript','java',str6)
print(e7)

#split()

In [ ]:
#search 
#findAll
#match
#sub()
#split()

import re
str = 'sun mop run man' 
 # m[a-z A-Z 0-9][a-z A-Z 0-9]
 #\w  [a-z A-Z 0-9]
 #\W ![a-z A-Z 0-9]
e = re.search(r'm\w\w',str)
#print(e)
#print(e.group())
if e:
    print('match found')
    print(e.group())
else:
    print('not found')

#program 2
str2 = 'sun mop run man mad' 
e2 = re.findall(r'm\w\w',str2)
#[] list is considered as falsy value in python
print(e2)
if e2:
    print('elements found')
    print(e2)
    for item in e2:
        print(item)
else:
    print('not found')

#program3
#match()
str3 = "qaq sad sun say some mad"
e4 = re.match(r's\w\w',str3)
if e4:
    print('pattern match')
    print(e4.group())
else:
    print('not found')

# search    object  none 
# findall   list     []
# match     object   None

#program 4
#replace
#sub
str4 = 'I am learning javascript'
e5 = re.sub(r'javascript','java',str4)
print(e5)


#program5
#Split()
str5 = 'This ; us the: "Core" Python\'s tutorial'
#str5 = 'ThisustheCorePythontutorial'
# [a-z] [A-Z] [0-9]
e7= re.split(r'\W+',str5)
print(e7)

# search    - object ---- none
# findall   - list   ---- []
# match     - obj    ---- none
# sub       - str    ----- str
# split     - list   ----- list

In [ ]:
# # \w [a-z][A-Z][0-9]

import re
# str = 'qas man sun mop run'
# e1 = re.search(r'm\w\w',str)
# if e1:
#     print('pattern find')
#     print(e1.group())
# else:
#     print('patter not found')

# # program 2
# str2 = 'qas man sun mop run'
# e2 = re.findall(r'm\w\w',str2)
# #[] falsy value
# if e2:
#     print('pattern found')
#     for item in e2:
#         print(item)
# else:
#     print('pattern not found')

# #program 3
# str3 ='mas man sun mop run'
# e3 = re.match(r'm\w\w',str3)
# if e3:
#     print('match found')
#     print(e3.group())
# else:
#     print('match not found')

# #program 4
# str4 = "i am learning javascript"
# e4 = re.sub(r'javascript','java',str4)
# print(e4)

# # program5
# #\W non alphanumeric not [a-z][A-Z][0-9]
str5 = 'This ; is the "Core" python\'s book'
e5 =re.split(r'\W+',str5)
print(e5)


e5 =re.split(r'\W',str5)
print(e5)

print("--------------------")
# #-----------------------------------------------------
# #\w  ===>  [a-z] [A-Z][0-9]
# #\b     ===> " "
# #\W     ===> not [a-z][A-Z][0-9]
# #\d     ===> [0,9]

str6 = 'an apple a day keeps the doctor away'
e6 = re.findall(r'\ba[\w]*\b',str6)
print(e6)
# e6 = re.findall(r'\ba[\w]*\b',str6)
# print(e6)

# #* 0 or more reptitions  0 > 2
# #+ 1 or more repetation  1, more repetion

# # an 
# # apple
# #away
# #ay
# #a
print("lllllllllllllllllllllllllll")
#program6
str7 = "I belong to 21st century not 19th century"
e7 = re.findall(r'\d[\w]*',str7)
print(e7)
e7 = re.findall(r'\d[\w]+',str7)
print(e7)
e7 = re.findall(r'\d[\w+]',str7)
print(e7)
e7 = re.findall(r'\d[\w*]',str7)
print(e7)



# e8 = re.findall(r'\d',str7)
# print(e8)


# # +
# # *
# # \b at the  beginning and ending


# # \w [a-z][A-Z][0-9]
# # \W not [a-z][A-Z][0-9]
# # \b  " "
# # \d [0-9]

print("lllllllllllllllllllllllllll")
a= "This is python support session"
# b=re.findall(r"[a-r]",a)
# print(b)
b=re.findall(r"\w\wp\w+",a)
print(b)
# b=re.findall(r"/bp[\w]*",a)
# print(b)



In [ ]:
import re 
# [a-z A-Z 0-9]
str = 'an apple a day keeps doctor away'
e  = re.findall(r'a[\w]*',str)
print(e)

e2 = re.findall(r'\ba[\w]*\b',str)
print(e2)

#program2
str2 = 'The meeting will be conducted on 1st and 21st of every month'
e3 = re.findall(r'\d[\w]*',str2)
print(e3)

#program3
str2 = "one two three four five six seven 8 9 10"
e4 = re.search(r'\b\w{5}\b',str2)
print(e4.group())

e5 = re.findall(r'\b\w{5}\b',str2) #[a-zA-z0-9]
print(e5)

#program4 (four or more)
e6 = re.findall(r'\b\w{4,}\b',str2)
print(e6)

#program5(minimum3 and maximum5)

e6 = re.findall(r'\b\w{3,5}\b',str2)
print(e6)

#str2 = "one two three four five six seven 8 9 10"
e7 = re.findall(r'\b\d{1,}\b',str2)
print(e7)

# Numpy


In [120]:
import numpy as np   # call
#      library  alias

In [124]:
# Create a 1D array
a = np.array([1, 2, 3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [123]:
a = numpy.array([1, 2, 3])

NameError: name 'numpy' is not defined

In [132]:
z = [1,2,3,4,5,6,7,8,9]
print(z)
print(type(z))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [134]:
b = np.array([2,3,4])
b

array([2, 3, 4])

In [135]:
b = np.array(z)
print(type(b))

<class 'numpy.ndarray'>


In [136]:
print(z)   # list
print(b)   # array

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [137]:
z*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [138]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [180]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [181]:
b = np.array([1, 4,6,8,8])

In [182]:
a+b

array([ 2,  6,  9, 12, 13])

In [10]:
a = "My name is \n Raj"
a

'My name is \n Raj'

In [11]:
print(a)

My name is 
 Raj


In [140]:
# Get the shape of an array
print(a.shape)

(5,)


float64


In [63]:
# Get the number of dimensions of an array
print(a.ndim)

1


In [45]:
# Creating arrays

# 1D array
a1 = np.arange(15) # same as range 
print(a1)
print(type(a1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [144]:
a1 = np.arange(5) # same as range 
print(a1)
print(type(a1))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [145]:
# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [146]:
#2D array

z2 = [[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8,9]]
a = np.array(z2)
print(a)
print(type(a))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
<class 'numpy.ndarray'>


In [147]:
# Get the shape of an array
print(a.shape)

(2, 9)


int32


In [149]:
# Get the number of dimensions of an array
print(a.ndim)

2


In [150]:
# creating array 

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [151]:
a = np.arange(15,25)
print(a)

[15 16 17 18 19 20 21 22 23 24]


In [152]:
a = np.arange(0,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [153]:
# np.arange(start,stop,stepsize)
a = np.arange(0,100,5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [154]:
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [157]:
a = list(range(0,100,0.5))
print(a)

TypeError: 'float' object cannot be interpreted as an integer

In [155]:
a = np.arange(0,10,.5) # fractional step count is allowed 
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
# reshape to convert the array dimension
# 2D array

In [158]:
a = np.arange(15)

In [159]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [160]:
a = np.arange(15).reshape(1,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


In [161]:
a = np.arange(15).reshape(2,7)
print(a)

ValueError: cannot reshape array of size 15 into shape (2,7)

In [162]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [165]:
a = np.arange(16).reshape(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [166]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [168]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [169]:
a = a.reshape(2,8) # Reshape 2x8
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [170]:
a = a.reshape(8,2) # Reshape 2x8
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [171]:
# using tuple
z1 = (1,2,3,4,5,6,7,8,9)
a1 = np.array(z1)
print(a1)
print(type(a1)) #<class 'numpy.ndarray'>

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [172]:
# creating 1d array

a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1)

[1 2 3 4 5 6 7 8 9]


In [173]:
a2 = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(a2)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [71]:
# creating 3d array
a3 = np.array([[[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]])
print(a3)

[[[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]]


In [72]:
print(a1.ndim) 
print(a2.ndim)
print(a3.ndim) # x/y/z axis count

1
2
3


In [74]:
a2 = np.array([[1.0,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(a2.dtype.name)
print(a2)

float64
[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [ ]:
# a2 = np.array([['1',2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
# print(a2.dtype.name)
# print(a2)

print(a2.size) # elements count
print(a1.size)
print(a3.size)